import { supabase,isSupabaseConfigured } from '../../lib/supabase'; import { studySetService } from '../../services/studySetService'; import { blocks,normalizeContent } from './utils'; import type { Annotation,Passage,PassageVersion,ReaderService } from './types';
const key='hugmo_topik_reader_v1'; const now=()=>new Date().toISOString(); const demoUser='demo-user-1234-5678-90ab-cdef12345678';
const fixture=()=>{const p=(id:string,title:string,content:string):[Passage,PassageVersion]=>{const v=id+'-v1';return[{id,user_id:demoUser,title,source_name:'Demo',source_url:null,topik_level:'INTERMEDIATE',notes:null,current_version_id:v,created_at:now(),updated_at:now()},{id:v,passage_id:id,version_number:1,content,content_hash:id,created_by:demoUser,created_at:now()}]};const [a,av]=p('demo-reader-1','환경 보호의 필요성','환경을 보호하기 위해 일회용품 사용을 줄여야 한다.\n\n사람들에게 작은 실천이 중요하다고 알렸다.');const[b,bv]=p('demo-reader-2','건강한 생활 습관','어려운 이웃을 돕고자 매년 봉사 활동에 참여하고 있다.');const make=(id:string,passage:Passage,version:PassageVersion,block:number,start:number,end:number,lemma:string,meaning:string):Annotation=>({id,user_id:demoUser,passage_id:passage.id,passage_version_id:version.id,block_index:block,start_offset:start,end_offset:end,selected_text:blocks(version.content)[block].slice(start,end),sentence_context:blocks(version.content)[block],lemma,part_of_speech:'VERB',meaning_vi:meaning,context_meaning_vi:null,pronunciation:null,morphemes:[],grammar_note_vi:null,confidence:'HIGH',user_corrected:false,analysis_provider:'fixture',analysis_provider_version:'1',created_at:now()});return{passages:[a,b],versions:[av,bv],annotations:[make('ann-1',a,av,0,20,23,'줄이다','giảm'),make('ann-2',a,av,0,0,3,'환경','môi trường'),make('ann-3',a,av,1,0,4,'사람','con người'),make('ann-4',b,bv,0,7,10,'돕다','giúp đỡ'),make('ann-5',b,bv,0,19,23,'참여하다','tham gia'),make('ann-6',b,bv,0,0,3,'어렵다','khó khăn')]};};
const demo=()=>{let d:any;try{d=JSON.parse(localStorage.getItem(key)||'');}catch{}if(!d){d=fixture();localStorage.setItem(key,JSON.stringify(d));}const save=()=>localStorage.setItem(key,JSON.stringify(d));return {async list(){return d.passages;},async get(id,versionId){const passage=d.passages.find((p:Passage)=>p.id===id);const version=d.versions.find((v:PassageVersion)=>v.id===(versionId||passage.current_version_id));return{passage,version,annotations:d.annotations.filter((a:Annotation)=>a.passage_version_id===version.id)};},async create(x){const id='reader-'+Date.now(),v=id+'-v1';const passage:any={id,user_id:x.userId,title:x.title,source_name:x.sourceName||null,source_url:x.sourceUrl||null,topik_level:x.level,notes:x.notes||null,current_version_id:v,created_at:now(),updated_at:now()};const version:any={id:v,passage_id:id,version_number:1,content:normalizeContent(x.content),content_hash:id,created_by:x.userId,created_at:now()};d.passages.unshift(passage);d.versions.push(version);save();return{passage,version};},async updateMetadata(id,x){Object.assign(d.passages.find((p:Passage)=>p.id===id),x,{updated_at:now()});save();},async createVersion(id,content){const passage=d.passages.find((p:Passage)=>p.id===id),n=Math.max(...d.versions.filter((v:PassageVersion)=>v.passage_id===id).map((v:PassageVersion)=>v.version_number))+1,v:any={id:id+'-v'+n,passage_id:id,version_number:n,content:normalizeContent(content),content_hash:id+n,created_by:passage.user_id,created_at:now()};d.versions.push(v);passage.current_version_id=v.id;save();return{passage,version:v};},async save(x){const id='ann-'+crypto.randomUUID();const a:any={id,user_id:x.userId,passage_id:x.version.passage_id,passage_version_id:x.version.id,...x.selection,lemma:x.analysis.lemma,part_of_speech:x.analysis.partOfSpeech,meaning_vi:x.analysis.meaningVi,context_meaning_vi:x.analysis.contextMeaningVi||null,pronunciation:null,morphemes:x.analysis.morphemes,grammar_note_vi:x.analysis.grammarNoteVi||null,confidence:x.analysis.confidence,user_corrected:false,analysis_provider:x.analysis.provider,analysis_provider_version:x.analysis.providerVersion,created_at:now()};d.annotations.push(a);save();return{annotation:a,flashcard:{id:x.reuseFlashcardId||'demo-card-'+Date.now(),study_set_id:x.studySetId,term:x.term,meaning:x.meaning}};}} as ReaderService;};
const live=():ReaderService=>({async list(userId){const{data,error}=await supabase.from('reading_passages').select('*').eq('user_id',userId).order('updated_at',{ascending:false});if(error)throw error;return data as Passage[];},async get(id,versionId){const{data:passage,error}=await supabase.from('reading_passages').select('*').eq('id',id).single();if(error)throw error;const vid=versionId||passage.current_version_id;const[{data:version,error:ve},{data:annotations,error:ae}]=await Promise.all([supabase.from('reading_passage_versions').select('*').eq('id',vid).single(),supabase.from('reading_annotations').select('*').eq('passage_version_id',vid).order('block_index').order('start_offset')]);if(ve||ae)throw ve||ae;return{passage:passage as Passage,version:version as PassageVersion,annotations:(annotations||[]) as Annotation[]};},async create(x){const{data,error}=await supabase.rpc('create_reading_passage',{p_title:x.title,p_content:normalizeContent(x.content),p_source_name:x.sourceName||null,p_source_url:x.sourceUrl||null,p_topik_level:x.level,p_notes:x.notes||null});if(error)throw error;return data as any;},async updateMetadata(id,x){const{error}=await supabase.from('reading_passages').update(x).eq('id',id);if(error)throw error;},async createVersion(id,content){const{data,error}=await supabase.rpc('create_reading_passage_version',{p_passage_id:id,p_content:normalizeContent(content)});if(error)throw error;return data as any;},async save(x){const{data,error}=await supabase.rpc('save_reading_word_to_passage_set',{p_version_id:x.version.id,p_block_index:x.selection.block_index,p_start_offset:x.selection.start_offset,p_end_offset:x.selection.end_offset,p_selected_text:x.selection.selected_text,p_sentence_context:x.selection.sentence_context,p_lemma:x.analysis.lemma,p_part_of_speech:x.analysis.partOfSpeech,p_meaning_vi:x.analysis.meaningVi,p_context_meaning_vi:x.analysis.contextMeaningVi||null,p_pronunciation:null,p_morphemes:x.analysis.morphemes,p_grammar_note_vi:x.analysis.grammarNoteVi||null,p_confidence:x.analysis.confidence,p_provider:x.analysis.provider,p_provider_version:x.analysis.providerVersion,p_term:x.term,p_meaning:x.meaning});if(error)throw error;return data as any;}});
export const readerService=(isDemo:boolean)=>isDemo||!isSupabaseConfigured?demo():live();
export async function getOrCreateReadingStudySet(passage:Passage,isDemo:boolean){
  if(isDemo||!isSupabaseConfigured){
    const mappingKey='hugmo_reader_study_set_ids'; let mapping:Record<string,string>={}; try{mapping=JSON.parse(localStorage.getItem(mappingKey)||'{}')}catch{}
    const sets=await studySetService.getStudySets(passage.user_id,true); const existing=sets.find(set=>set.id===mapping[passage.id]);
    if(existing)return existing;
    const created=await studySetService.createStudySet(passage.user_id,`Tu vung - ${passage.title}`,'Vocabulary saved from this reading.',[],true);
    mapping[passage.id]=created.id; localStorage.setItem(mappingKey,JSON.stringify(mapping)); return created;
  }
  const{data,error}=await supabase.rpc('get_or_create_reading_study_set',{p_passage_id:passage.id}); if(error)throw error; return data as {id:string;title:string};
}
export async function flashcardReaderContexts(flashcardIds:string[],isDemo:boolean){if(!flashcardIds.length)return[] as Array<{flashcardId:string;passageId:string;annotationId:string;title:string;context:string}>;if(isDemo)return flashcardIds.includes('card-1')?[{flashcardId:'card-1',passageId:'demo-reader-1',annotationId:'ann-2',title:'환경 보호의 필요성',context:'환경을 보호하기 위해 일회용품 사용을 줄여야 한다.'}]:[];const{data,error}=await supabase.from('reading_flashcard_links').select('flashcard_id,reading_annotations(id,passage_id,sentence_context,reading_passages(title))').in('flashcard_id',flashcardIds);if(error)throw error;return(data||[]).map((row:any)=>({flashcardId:row.flashcard_id,passageId:row.reading_annotations.passage_id,annotationId:row.reading_annotations.id,title:row.reading_annotations.reading_passages.title,context:row.reading_annotations.sentence_context}));}
