-- Generated from seed/sources/TOPIK_READING_20_21_SEED_DATA.json. Do not hand-edit canonical source data.
-- Regenerate with: node scripts/topikReading2021Seed.mjs
begin;
insert into public.topik_sources(source_key, title, edition, scope, notes) values ('TOPIK_3_4_PHUONG_ANH_READING_20_21', 'Chinh phục TOPIK 3-4 – Tiếng Hàn Phương Anh', 'TOPIK 3-4. B11(2).pdf', 'TOPIK II Reading 20-21', 'Sách tổ chức theo cặp 19–20 và 21–22. Dataset tập trung kỹ năng câu 20 (chủ đề/nội dung trọng tâm) và câu 21 (관용 표현), đồng thời giữ câu 19/22 đi kèm để bảo toàn ngữ cảnh bài gốc.') on conflict (source_key) do update set title = excluded.title, edition = excluded.edition, scope = excluded.scope, notes = excluded.notes;

insert into public.topik_reading_idiom_groups(code, name_ko, name_vi, sort_order) values
  ('EYE', '눈 / 시선', 'Mắt / ánh nhìn', 1),
  ('MOUTH_TASTE', '입·혀·이 / 말·감정', 'Miệng / lưỡi / răng / lời nói', 2),
  ('EAR', '귀 / 듣기', 'Tai / nghe', 3),
  ('HAND', '손 / 행동', 'Tay / hành động', 4),
  ('FOOT', '발 / 이동·관계', 'Chân / di chuyển / quan hệ', 5),
  ('HEAD_FACE', '머리·고개·얼굴·목·코', 'Đầu / mặt / cổ / mũi', 6),
  ('CHEST_MIND', '가슴·마음', 'Ngực / tâm trạng / ý chí', 7),
  ('TORSO', '어깨·등·허리·배', 'Vai / lưng / eo / bụng', 8),
  ('BODY_REACTION', '신체 반응', 'Phản ứng cơ thể', 9),
  ('ABSTRACT_ACTION', '판단·행동 표현', 'Phán đoán / hành động trừu tượng', 10),
  ('PROVERB_METAPHOR', '속담·비유 표현', 'Tục ngữ / biểu hiện ẩn dụ', 11)
on conflict (code) do update set name_ko = excluded.name_ko, name_vi = excluded.name_vi, sort_order = excluded.sort_order;

insert into public.topik_reading_idioms(expression_ko, meaning_vi_source, memory_group_code, body_part, core_verb, core_verb_vi_editorial, priority, source_type, review_status, review_note, status) values
  ('가슴을 울리다', 'cảm động sâu sắc', 'CHEST_MIND', '가슴', '울리다', 'làm rung, lay động', 'A', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('허리띠를 졸라매다', 'thắt lưng buộc bụng, chịu khó, tiết kiệm', 'TORSO', '허리띠', '졸라매다', 'siết/chặt', 'S', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('한눈에 보이다', 'dễ nhận ra', 'EYE', '눈', '보이다', 'được nhìn thấy', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('마음을 먹다', 'quyết tâm', 'CHEST_MIND', '마음', '먹다', 'ăn; trong cụm này mang nghĩa quyết tâm', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('입이 벌어지다', 'há hốc miệng (ngạc nhiên, sốc...)', 'MOUTH_TASTE', '입', '벌어지다', 'mở rộng, há ra', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('눈감아 주다', 'nhắm mắt cho qua', 'EYE', '눈', '감다', 'nhắm', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('손에 땀을 쥐다', '“tay toát mồ hôi” - căng thẳng, hồi hộp', 'HAND', '손', '쥐다', 'nắm', 'A', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('입을 다물게 하다', 'khiến ai cứng họng, không thể nói lại', 'MOUTH_TASTE', '입', '다물다', 'khép, ngậm', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('물 샐 틈 없이', 'chặt chẽ, không sơ hở', 'PROVERB_METAPHOR', null, null, null, 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('등을 돌리다', 'quay lưng, rời bỏ', 'TORSO', '등', '돌리다', 'quay', 'A', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('날개 돋친 듯이', 'bán chạy, cháy hàng', 'PROVERB_METAPHOR', null, '돋치다', 'mọc, nhú', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('귓등으로 듣다', '“nghe bằng vành tai ngoài” - làm lơ, bỏ ngoài tai', 'EAR', '귀', '듣다', 'nghe', 'A', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('손이 발이 되다', '“Tay trở thành chân” - luống cuống, rối rít', 'HAND', '손/발', '되다', 'trở thành', 'B', 'SOURCE_BOOK', 'NEEDS_REVIEW', 'Biểu thức được giữ nguyên theo text parse của sách; nên kiểm tra lại ảnh trang 76 trước khi public.', 'PUBLISHED'),
  ('발 벗고 나서다', '“cởi giày nhảy vào giúp đỡ” - hết lòng giúp đỡ', 'FOOT', '발', '나서다', 'đứng ra, bước ra', 'S', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('콧대가 높다', 'kiêu căng, tự cao', 'HEAD_FACE', '코', '높다', 'cao', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('그림의 떡', '“Bánh tteok trong tranh” - thứ chỉ có thể nhìn mà không thể có được', 'PROVERB_METAPHOR', null, null, null, 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('귀에 못이 박히다', '“Tai bị đóng đinh” - nghe phát chán', 'EAR', '귀', '박히다', 'bị đóng/cắm vào', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('새발의 피', '“Máu ở chân chim” - rất ít, rất nhỏ, chẳng thấm vào đâu', 'PROVERB_METAPHOR', null, null, null, 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('우물 안 개구리', 'Ếch ngồi đáy giếng', 'PROVERB_METAPHOR', null, null, null, 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('티끌 모아 태산', 'Tích tiểu thành đại', 'PROVERB_METAPHOR', null, '모으다', 'gom, tích lại', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('콧대를 꺾다', 'làm ai đó bớt kiêu căng / dạy cho một bài học', 'HEAD_FACE', '코', '꺾다', 'bẻ, làm gãy', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('발걸음을 맞추다', 'phối hợp ăn ý, hòa hợp trong hành động hoặc mối quan hệ', 'FOOT', '발걸음', '맞추다', 'làm cho khớp, phối hợp', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('어깨를 가볍게 하다', 'trút được gánh nặng, thấy nhẹ nhõm', 'TORSO', '어깨', '가볍게 하다', 'làm cho nhẹ', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('눈살을 찌푸리다', 'tỏ ra khó chịu, không hài lòng, bực mình', 'EYE', '눈', '찌푸리다', 'nhíu, cau', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('발을 빼다', '“Rút chân ra” - rút lui khỏi việc đang làm, phủi trách nhiệm, không tham gia nữa', 'FOOT', '발', '빼다', 'rút ra', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('등을 떠밀다', '“Đẩy vào lưng” - thúc ép ai làm việc gì', 'TORSO', '등', '떠밀다', 'đẩy, thúc', 'A', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('손을 맞잡다', '“Nắm tay nhau” - hợp tác, đoàn kết, đồng lòng', 'HAND', '손', '맞잡다', 'nắm lấy nhau', 'A', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('어깨를 펴다', '“Duỗi vai ra” - tự tin, kiêu hãnh, không còn mặc cảm', 'TORSO', '어깨', '펴다', 'duỗi, mở ra', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('고개를 들다', '“Ngẩng đầu lên” - có hy vọng, tự tin trở lại', 'HEAD_FACE', '고개', '들다', 'nâng, ngẩng', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('진땀을 흘리다', '“Đổ mồ hôi hột” - rơi vào tình huống căng thẳng, áp lực', 'BODY_REACTION', '진땀', '흘리다', 'đổ, chảy', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('허리를 굽히다', '“Cúi lưng” - khiêm nhường, nhún nhường, cúi mình', 'TORSO', '허리', '굽히다', 'cúi, gập', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('마음을 졸이다', '“Tim co thắt lại” - lo lắng, hồi hộp, thấp thỏm', 'CHEST_MIND', '마음', '졸이다', 'làm co/rút; thấp thỏm', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('얼굴이 피다', '“Khuôn mặt nở ra” - gương mặt trở bừng sáng, rạng rỡ', 'HEAD_FACE', '얼굴', '피다', 'nở', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('호흡을 맞추다', '“Đồng bộ hơi thở” - phối hợp ăn ý', 'BODY_REACTION', '호흡', '맞추다', 'làm cho khớp, phối hợp', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('눈을 딱 감다', 'cắn răng chịu đựng mà làm', 'EYE', '눈', '감다', 'nhắm', 'A', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('목에 힘을 주다', '“Căng cơ cổ” - vênh váo, kiêu ngạo, lên mặt', 'HEAD_FACE', '목', '힘을 주다', 'dồn/đặt sức vào', 'A', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('머리를 맞대다', '“Chụm đầu lại với nhau” - cùng thảo luận, suy nghĩ', 'HEAD_FACE', '머리', '맞대다', 'áp/chụm vào nhau', 'S', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('입맛에 맞다', '“Hợp khẩu vị” - hợp gu / vừa ý', 'MOUTH_TASTE', '입맛', '맞다', 'hợp, vừa', 'A', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('손을 떼다', '“Rút tay ra” - rút khỏi / buông tay / không dính líu', 'HAND', '손', '떼다', 'tách, rời', 'S', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('발목을 잡다', '“Nắm cổ chân” - gây cản trở, kìm chân', 'FOOT', '발목', '잡다', 'nắm, giữ', 'S', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('이를 가다', '“Nghiến răng” - tức sôi máu, căm tức', 'MOUTH_TASTE', '이', '갈다', 'nghiến/mài', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('담을 쌓다', '“Xây tường” - cắt đứt quan hệ, quay lưng', 'PROVERB_METAPHOR', null, '쌓다', 'xây, đắp', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('열을 올리다', '“Tăng nhiệt” - lên mood, hăng say / nóng máu, nóng giận', 'BODY_REACTION', '열', '올리다', 'nâng lên', 'A', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('앞뒤를 재다', 'cân nhắc kỹ lưỡng', 'ABSTRACT_ACTION', null, '재다', 'đo, cân nhắc', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('발을 끊다', 'cắt đứt quan hệ / không lui tới nữa', 'FOOT', '발', '끊다', 'cắt, ngắt', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('앞뒤를 가리지 않다', '“Không phân biệt trước sau” - không suy nghĩ, bốc đồng', 'ABSTRACT_ACTION', null, '가리다', 'phân biệt', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('못을 박다', '“Đóng đinh” - khẳng định chắc chắn / làm tổn thương', 'PROVERB_METAPHOR', null, '박다', 'đóng, cắm', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('고개를 숙이다', '“Cúi đầu” - hối lỗi, nhận sai / cảm thấy xấu hổ', 'HEAD_FACE', '고개', '숙이다', 'cúi xuống', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('제 눈의 안경', '“Kính của chính mình” - mỗi người một gu, mình thấy đẹp là được', 'EYE', '눈', null, null, 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('엎질러진 물', '“Nước đã bị đổ” - việc đã xảy ra thì không thể quay lại được', 'PROVERB_METAPHOR', null, null, null, 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('싼 게 비지떡', '“Đồ rẻ là bánh bã đậu” - đồ rẻ thì chất lượng cũng thấp', 'PROVERB_METAPHOR', null, null, null, 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('입 밖에 내다', '“Đưa ra ngoài miệng” - nói ra (điều khó nói)', 'MOUTH_TASTE', '입', '내다', 'đưa ra', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('한 술 더 뜨다', '“Múc thêm một muỗng” - thêm dầu vào lửa', 'PROVERB_METAPHOR', null, '뜨다', 'múc', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('하나를 보면 열을 알다', 'Nhìn một là biết mười', 'PROVERB_METAPHOR', null, '알다', 'biết', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('천 리 길도 한 걸음부터', '“Vạn dặm đường bắt đầu từ một bước chân” - mọi việc lớn đều phải bắt đầu từ những bước nhỏ', 'PROVERB_METAPHOR', null, null, null, 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('소 잃고 외양간 고치다', 'Mất bò mới lo làm chuồng', 'PROVERB_METAPHOR', null, '고치다', 'sửa', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('윗물이 맑아야 아랫물이 맑다', '“Nước đầu nguồn trong thì nước hạ lưu mới trong” - người trên sống đúng đắn thì người dưới mới noi theo', 'PROVERB_METAPHOR', null, '맑다', 'trong, sạch', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('귀를 기울이다', '“Nghiêng tai” - chú ý lắng nghe', 'EAR', '귀', '기울이다', 'nghiêng', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('위아래 없이', '“Không trên không dưới” - không phân biệt vai vế, không giữ lễ nghi', 'ABSTRACT_ACTION', null, null, null, 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('도토리 키 재기', 'so sánh một chín một mười', 'PROVERB_METAPHOR', null, '재다', 'đo, so', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('하늘의 별 따기', '“Hái sao trên trời” - rất khó, như mò kim đáy bể', 'PROVERB_METAPHOR', null, '따다', 'hái', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('누워서 떡 먹기', '“Nằm ăn bánh tteok” - dễ như ăn kẹo / dễ như trở bàn tay', 'PROVERB_METAPHOR', null, '먹다', 'ăn', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('손 안 대고 코 풀기', '“Hỉ mũi mà không dùng tay” - muốn ăn mà chẳng muốn làm', 'HAND', '손/코', '풀다', 'xì/hỉ', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('혀를 차다', '“Tặc lưỡi” - chán nản, thất vọng hoặc không hài lòng', 'MOUTH_TASTE', '혀', '차다', 'tặc/chậc lưỡi', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('갈피를 못 잡다', '“Không nắm được đầu mối” - bối rối, không xác định được phương hướng', 'ABSTRACT_ACTION', null, '잡다', 'nắm', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('눈 깜짝할 사이', 'trong chớp mắt', 'EYE', '눈', '깜짝하다', 'chớp', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('눈에 핏발이 서다', '“Mắt đỏ ngầu” - rất tức giận hoặc rất mệt mỏi/căng thẳng', 'EYE', '눈', '서다', 'nổi/đứng', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('눈 뜨고 볼 수 없다', '“Không thể mở mắt ra nhìn” - cảnh tượng quá tệ, đến mức không dám nhìn', 'EYE', '눈', '뜨다/보다', 'mở mắt / nhìn', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('눈독을 들이다', 'để mắt tới, nhăm nhe', 'EYE', '눈', '들이다', 'đưa vào, hướng vào', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('시치미를 떼다', 'giả vờ không biết, giả nai', 'PROVERB_METAPHOR', null, '떼다', 'tách/rời', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('찬물을 끼얹다', 'dội gáo nước lạnh, phá bầu không khí', 'PROVERB_METAPHOR', null, '끼얹다', 'dội, hắt', 'A', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('물불 가리지 않다', '“Không phân biệt nước với lửa” - bất chấp tất cả, liều lĩnh, không ngại gì', 'PROVERB_METAPHOR', null, '가리다', 'phân biệt', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('입을 모으다', 'đồng thanh nhất trí, đều đồng ý', 'MOUTH_TASTE', '입', '모으다', 'gom, tập hợp', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('배를 두드리다', '“Vỗ bụng” - cảm giác no nê / thoải mái, thỏa mãn, hài lòng', 'TORSO', '배', '두드리다', 'vỗ', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('눈에 불을 켜다', '“Trong mắt có lửa” - cực kỳ chăm chú, đổ dồn sự chú ý vào', 'EYE', '눈', '켜다', 'bật', 'B', 'SOURCE_BOOK', 'VERIFIED', null, 'PUBLISHED'),
  ('눈을 맞추다', null, 'EYE', '눈', '맞추다', null, 'A', 'SOURCE_BOOK', 'NEEDS_GLOSS', 'Biểu thức xuất hiện trong lựa chọn câu 21 nhưng sách không cho nghĩa tiếng Việt ở bảng 관용 표현; không tự điền nghĩa vào trường source.', 'PUBLISHED'),
  ('맛을 보다', null, 'MOUTH_TASTE', '입맛/맛', '보다', null, 'A', 'SOURCE_BOOK', 'NEEDS_GLOSS', 'Biểu thức xuất hiện trong lựa chọn câu 21 nhưng sách không cho nghĩa tiếng Việt ở bảng 관용 표현; không tự điền nghĩa vào trường source.', 'PUBLISHED'),
  ('문을 두드리다', null, 'PROVERB_METAPHOR', null, '두드리다', null, 'A', 'SOURCE_BOOK', 'NEEDS_GLOSS', 'Biểu thức xuất hiện trong lựa chọn câu 21 nhưng sách không cho nghĩa tiếng Việt ở bảng 관용 표현; không tự điền nghĩa vào trường source.', 'PUBLISHED'),
  ('손에 잡히다', null, 'HAND', '손', '잡히다', null, 'A', 'SOURCE_BOOK', 'NEEDS_GLOSS', 'Biểu thức xuất hiện trong lựa chọn câu 21 nhưng sách không cho nghĩa tiếng Việt ở bảng 관용 표현; không tự điền nghĩa vào trường source.', 'PUBLISHED'),
  ('손에 꼽히다', null, 'HAND', '손', '꼽히다', null, 'S', 'SOURCE_BOOK', 'NEEDS_GLOSS', 'Biểu thức xuất hiện trong lựa chọn câu 21 nhưng sách không cho nghĩa tiếng Việt ở bảng 관용 표현; không tự điền nghĩa vào trường source.', 'PUBLISHED'),
  ('눈에 걸리다', null, 'EYE', '눈', '걸리다', null, 'A', 'SOURCE_BOOK', 'NEEDS_GLOSS', 'Biểu thức xuất hiện trong lựa chọn câu 21 nhưng sách không cho nghĩa tiếng Việt ở bảng 관용 표현; không tự điền nghĩa vào trường source.', 'PUBLISHED'),
  ('눈에 밟히다', null, 'EYE', '눈', '밟히다', null, 'A', 'SOURCE_BOOK', 'NEEDS_GLOSS', 'Biểu thức xuất hiện trong lựa chọn câu 21 nhưng sách không cho nghĩa tiếng Việt ở bảng 관용 표현; không tự điền nghĩa vào trường source.', 'PUBLISHED'),
  ('손에 익다', null, 'HAND', '손', '익다', null, 'A', 'SOURCE_BOOK', 'NEEDS_GLOSS', 'Biểu thức xuất hiện trong lựa chọn câu 21 nhưng sách không cho nghĩa tiếng Việt ở bảng 관용 표현; không tự điền nghĩa vào trường source.', 'PUBLISHED'),
  ('발이 넓다', null, 'FOOT', '발', '넓다', null, 'A', 'SOURCE_BOOK', 'NEEDS_GLOSS', 'Biểu thức xuất hiện trong lựa chọn câu 21 nhưng sách không cho nghĩa tiếng Việt ở bảng 관용 표현; không tự điền nghĩa vào trường source.', 'PUBLISHED'),
  ('눈길을 끌다', null, 'EYE', '눈길', '끌다', null, 'A', 'SOURCE_BOOK', 'NEEDS_GLOSS', 'Biểu thức xuất hiện trong lựa chọn câu 21 nhưng sách không cho nghĩa tiếng Việt ở bảng 관용 표현; không tự điền nghĩa vào trường source.', 'PUBLISHED'),
  ('눈높이에 맞다', null, 'EYE', '눈높이', '맞다', null, 'S', 'SOURCE_BOOK', 'NEEDS_GLOSS', 'Biểu thức xuất hiện trong lựa chọn câu 21 nhưng sách không cho nghĩa tiếng Việt ở bảng 관용 표현; không tự điền nghĩa vào trường source.', 'PUBLISHED'),
  ('발뺌을 하다', null, 'FOOT', '발', '발뺌을 하다', null, 'A', 'SOURCE_BOOK', 'NEEDS_GLOSS', 'Biểu thức xuất hiện trong lựa chọn câu 21 nhưng sách không cho nghĩa tiếng Việt ở bảng 관용 표현; không tự điền nghĩa vào trường source.', 'PUBLISHED'),
  ('한 우물을 파다', null, 'PROVERB_METAPHOR', null, '파다', null, 'A', 'SOURCE_BOOK', 'NEEDS_GLOSS', 'Biểu thức xuất hiện trong lựa chọn câu 21 nhưng sách không cho nghĩa tiếng Việt ở bảng 관용 표현; không tự điền nghĩa vào trường source.', 'PUBLISHED')
on conflict (expression_ko) do update set meaning_vi_source = excluded.meaning_vi_source, memory_group_code = excluded.memory_group_code, body_part = excluded.body_part, core_verb = excluded.core_verb, core_verb_vi_editorial = excluded.core_verb_vi_editorial, priority = excluded.priority, source_type = excluded.source_type, review_status = excluded.review_status, review_note = excluded.review_note, status = excluded.status;

insert into public.topik_reading_idiom_aliases(idiom_id, alias_ko) values
  ((select id from public.topik_reading_idioms where expression_ko = '눈감아 주다'), '눈을 감아 주다')
on conflict (idiom_id, alias_ko) do nothing;

insert into public.topik_reading_source_locations(entity_type, entity_id, source_page, source_kind) values
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '가슴을 울리다'), 75, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '가슴을 울리다'), 81, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '허리띠를 졸라매다'), 75, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '허리띠를 졸라매다'), 86, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '한눈에 보이다'), 75, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '마음을 먹다'), 75, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '입이 벌어지다'), 75, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '눈감아 주다'), 75, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '손에 땀을 쥐다'), 75, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '손에 땀을 쥐다'), 80, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '손에 땀을 쥐다'), 82, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '입을 다물게 하다'), 75, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '물 샐 틈 없이'), 75, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '등을 돌리다'), 75, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '등을 돌리다'), 86, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '날개 돋친 듯이'), 75, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '귓등으로 듣다'), 75, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '귓등으로 듣다'), 87, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '손이 발이 되다'), 76, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '발 벗고 나서다'), 76, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '발 벗고 나서다'), 82, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '발 벗고 나서다'), 87, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '콧대가 높다'), 76, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '그림의 떡'), 76, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '귀에 못이 박히다'), 76, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '새발의 피'), 76, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '우물 안 개구리'), 76, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '티끌 모아 태산'), 76, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '콧대를 꺾다'), 76, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '발걸음을 맞추다'), 76, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '발걸음을 맞추다'), 77, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '어깨를 가볍게 하다'), 76, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '눈살을 찌푸리다'), 76, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '발을 빼다'), 76, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '등을 떠밀다'), 76, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '등을 떠밀다'), 82, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '손을 맞잡다'), 76, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '손을 맞잡다'), 81, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '어깨를 펴다'), 76, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '고개를 들다'), 76, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '진땀을 흘리다'), 76, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '허리를 굽히다'), 77, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '마음을 졸이다'), 77, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '얼굴이 피다'), 77, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '호흡을 맞추다'), 77, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '눈을 딱 감다'), 77, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '눈을 딱 감다'), 80, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '목에 힘을 주다'), 77, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '목에 힘을 주다'), 80, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '머리를 맞대다'), 77, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '머리를 맞대다'), 80, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '입맛에 맞다'), 77, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '입맛에 맞다'), 81, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '손을 떼다'), 77, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '손을 떼다'), 83, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '손을 떼다'), 86, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '발목을 잡다'), 77, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '발목을 잡다'), 81, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '이를 가다'), 77, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '담을 쌓다'), 77, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '열을 올리다'), 77, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '열을 올리다'), 83, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '앞뒤를 재다'), 77, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '발을 끊다'), 77, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '앞뒤를 가리지 않다'), 77, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '못을 박다'), 77, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '고개를 숙이다'), 78, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '제 눈의 안경'), 78, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '엎질러진 물'), 78, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '싼 게 비지떡'), 78, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '입 밖에 내다'), 78, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '한 술 더 뜨다'), 78, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '하나를 보면 열을 알다'), 78, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '천 리 길도 한 걸음부터'), 78, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '소 잃고 외양간 고치다'), 78, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '윗물이 맑아야 아랫물이 맑다'), 78, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '귀를 기울이다'), 78, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '위아래 없이'), 78, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '도토리 키 재기'), 78, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '하늘의 별 따기'), 78, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '누워서 떡 먹기'), 78, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '손 안 대고 코 풀기'), 78, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '혀를 차다'), 79, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '갈피를 못 잡다'), 79, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '눈 깜짝할 사이'), 79, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '눈에 핏발이 서다'), 79, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '눈 뜨고 볼 수 없다'), 79, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '눈독을 들이다'), 79, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '시치미를 떼다'), 79, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '찬물을 끼얹다'), 79, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '찬물을 끼얹다'), 87, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '물불 가리지 않다'), 79, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '입을 모으다'), 79, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '배를 두드리다'), 79, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '눈에 불을 켜다'), 79, 'IDIOM_GLOSSARY'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '눈을 맞추다'), 82, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '눈을 맞추다'), 82, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '맛을 보다'), 83, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '맛을 보다'), 83, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '문을 두드리다'), 83, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '문을 두드리다'), 83, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '손에 잡히다'), 84, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '손에 잡히다'), 84, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '손에 꼽히다'), 84, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '손에 꼽히다'), 84, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '눈에 걸리다'), 84, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '눈에 걸리다'), 84, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '눈에 밟히다'), 84, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '눈에 밟히다'), 84, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '손에 익다'), 85, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '손에 익다'), 85, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '발이 넓다'), 85, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '발이 넓다'), 85, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '눈길을 끌다'), 85, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '눈길을 끌다'), 85, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '눈높이에 맞다'), 85, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '눈높이에 맞다'), 85, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '발뺌을 하다'), 86, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '발뺌을 하다'), 86, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '한 우물을 파다'), 87, 'Q21_OPTION'),
  ('IDIOM', (select id from public.topik_reading_idioms where expression_ko = '한 우물을 파다'), 87, 'Q21_OPTION')
on conflict (entity_type, entity_id, source_page, source_kind) do nothing;

insert into public.topik_reading_20_21_exercises(source_key, source_id, question_pair, set_type, source_page, passage_ko, status, source_type) values
  ('READING_19_20_SAMPLE_01', (select id from public.topik_sources where source_key = 'TOPIK_3_4_PHUONG_ANH_READING_20_21'), '19_20', 'SAMPLE', 67, '좋은 생각을 끌어내려면 질문을 어떻게 할지 잘 고민해야 한다. 어떤 회사에서 신제품을 만들고자 직원에게 질문을 한다고 치자. “어떤 물건이 잘 팔릴까?”라고 막연하게 질문하면 대답이 잘 나오지 않는다. 좋은 질문이 아니기 때문이다. ( ) “지금까지의 제품에서 무엇을 개선할까?”라고 질문하면 도움이 되는 구체적인 답이 나온다.', 'PUBLISHED', 'SOURCE_BOOK'),
  ('READING_19_20_SAMPLE_02', (select id from public.topik_sources where source_key = 'TOPIK_3_4_PHUONG_ANH_READING_20_21'), '19_20', 'SAMPLE', 68, '매서운 남극의 겨울, 황제펭귄들은 겹겹이 붙어 서로의 체온으로 추위를 견딘다. 무리 전체가 돌면서 바깥쪽과 안쪽에 있는 펭귄들이 계속 서로의 위치를 바꾼다. 안에서 몸을 데운 펭귄은 밖으로 나가고 밖에서 추위에 떨던 펭귄은 안으로 들어오는 것이다. ( ) 그 움직임은 아주 느리지만 쉬지 않고 이루어져 한 마리의 펭귄이 줄곧 찬바람을 맞고 서 있는 일이 없다. 그렇게 쉼 없이 둥글게 돌면서 펭귄들은 다 함께 살아남는다.', 'PUBLISHED', 'SOURCE_BOOK'),
  ('READING_19_20_SAMPLE_03', (select id from public.topik_sources where source_key = 'TOPIK_3_4_PHUONG_ANH_READING_20_21'), '19_20', 'SAMPLE', 69, '흥미와 재미 요소를 내세워 홍보하는 마케팅 전략이 주목받고 있다. 이런 마케팅은 소비자의 호기심을 자극해 구매로 이어지게 한다. 그러나 제품의 품질이 소비자의 기대에 미치지 못하는 경우 ( ) 브랜드 이미지까지 나빠지기도 한다. 실제로 한 햄버거 회사에서 ‘주머니 버거’, ‘눌러 먹는 버거’를 만들어 소비자의 관심을 끌었지만 품질이 기대에 못 미치자 회사의 다른 제품까지 판매가 감소한 경우가 있었다.', 'PUBLISHED', 'SOURCE_BOOK'),
  ('READING_19_20_PRACTICE_01', (select id from public.topik_sources where source_key = 'TOPIK_3_4_PHUONG_ANH_READING_20_21'), '19_20', 'PRACTICE', 70, '달걀은 영양가가 높은 식품이지만 콜레스테롤 때문에 별로 즐기지 않는 사람들도 많다. 그러나 연구에 의하면 하루에 달걀 한 개를 먹는 사람은 ( ) 먹지 않는 사람에 비해 심장 관련 질병에 걸릴 가능성이 적었다. 그렇다면 건강을 위한 ‘달걀 잘 먹는 방법’에는 어떤 것이 있을까? 먼저 신선한 달걀을 고를 줄 알아야 한다. 신선한 달걀은 껍질 표면이 매끈하고 빛이 나는 것이다. 그리고 구매한 달걀은 냉장고에 보관해야 한다. 또한 달걀을 찬물에 넣었을 때 가라앉으면 싱싱한 것이지만 물 위로 뜨면 상한 것이므로 먹어서는 안 된다.', 'PUBLISHED', 'SOURCE_BOOK'),
  ('READING_19_20_PRACTICE_02', (select id from public.topik_sources where source_key = 'TOPIK_3_4_PHUONG_ANH_READING_20_21'), '19_20', 'PRACTICE', 71, '우리는 자신과 남들을 비교하며 감사보다는 불평을 하는 경우가 많다. 부동산 가격이 올라 몇 배의 이익을 보았다는 주변의 이야기를 듣고 상대적 박탈감을 느끼는 어른들, 줄 세우기식 교육으로 인해 갈수록 자존감을 잃어가는 자녀들의 삶이 그 예이다. ( ) 우리에게는 돌아갈 집과 따뜻한 가족이 있고 성적보다 더 중요한 친구들이 있다는 것을 기억했으면 한다. 그리고 상대방이 소유한 것에 대해 부러워하기보다는 자신이 갖고 있는 것에 만족할 때 감사하는 삶을 살 수 있음을 잊지 말아야 한다.', 'PUBLISHED', 'SOURCE_BOOK'),
  ('READING_19_20_PRACTICE_03', (select id from public.topik_sources where source_key = 'TOPIK_3_4_PHUONG_ANH_READING_20_21'), '19_20', 'PRACTICE', 72, '부모는 아이가 어릴 때 아이를 보호해 준다. 유치원이나 초등학교에 갈 때는 손을 잡고 함께 걷는다. 그러나 아이가 크면 부모는 아이의 뒤에서 걸어야 한다. 이것은 아이에게 선택의 자유를 주기 위해서다. ( ) 아이는 스스로 생각하고 판단하는 능력을 키우기 어렵다. 어떤 일을 할 때도 부모가 선택한 것을 강요하기보다는 아이가 스스로 선택하여 행동할 수 있도록 하는 것이 아이의 자아 성장을 위해 바람직하다.', 'PUBLISHED', 'SOURCE_BOOK'),
  ('READING_19_20_PRACTICE_04', (select id from public.topik_sources where source_key = 'TOPIK_3_4_PHUONG_ANH_READING_20_21'), '19_20', 'PRACTICE', 73, '핵가족이 늘고 은퇴 후에 자녀들과 따로 살기를 원하는 노인들이 늘면서 실버타운에 대한 관심도 높아지고 있다. 최근에는 고급 실버타운이 큰 인기를 끌고 있는데 가격은 비싸지만 의료 시설과 편의 시설이 모두 갖춰져 있어서 생활하기에 아주 편리하기 때문이다. 과거에는 도시에서 일하던 사람들이 은퇴 후 다시 고향에 돌아가 노후를 보내기 원했기 때문에 주로 한적한 시골에 실버타운을 건설했다. 그러나 시대가 바뀌면서 요즘은 ( ) 도시 생활을 편하게 생각하는 노인이 많아져서 도시나 도시 근교에 실버타운을 짓는 경우가 늘고 있다.', 'PUBLISHED', 'SOURCE_BOOK'),
  ('READING_19_20_PRACTICE_05', (select id from public.topik_sources where source_key = 'TOPIK_3_4_PHUONG_ANH_READING_20_21'), '19_20', 'PRACTICE', 74, '새집으로 이사한 후부터 전에 없던 이상한 증상이 나타나기 시작했다면 새집 증후군을 의심해 볼 수 있다. 집을 지을 때 사용한 건축자재에서 나온 화학 물질이 집 안의 공기를 오염시켰을 가능성이 있기 때문이다. ( ) 새집에서 두통, 어지러움, 비염, 천식 등 알레르기 증상이 나타난다면 환기에 특히 신경을 써야 한다. 집을 자주 청소하고 공기를 깨끗하게 해주는 식물을 키우는 것도 좋다.', 'PUBLISHED', 'SOURCE_BOOK'),
  ('READING_21_22_SAMPLE_01', (select id from public.topik_sources where source_key = 'TOPIK_3_4_PHUONG_ANH_READING_20_21'), '21_22', 'SAMPLE', 80, '학생 수 감소로 폐교가 될 뻔한 산골 초등학교가 위기에서 벗어나 화제이다. 이 학교 선생님들은 ( ) 학교를 살릴 방법을 고민했다. 그러다 찾은 것이 ‘음악 특성화 학교’였다. 선생님들은 예술대학교에 협조를 요청해 학생들에게 다양한 악기를 가르칠 전문가를 구했다. 또 기업의 기부를 받아 유명 음악가와 함께하는 음악회도 개최했다. 이런 소문을 듣고 음악을 배우러 오는 학생들이 생기면서 이 학교는 폐교 위기에서 벗어났다.', 'PUBLISHED', 'SOURCE_BOOK'),
  ('READING_21_22_SAMPLE_02', (select id from public.topik_sources where source_key = 'TOPIK_3_4_PHUONG_ANH_READING_20_21'), '21_22', 'SAMPLE', 81, '최근 미술 전시회 수요가 증가하면서 돈벌이에 급급한 전시회가 늘고 있다. 일부 전시 관계자들이 전시 포스터 등 홍보 자료에 복제품 전시임을 밝히지 않고 입장료 수입만을 챙기는 것이다. 전시장을 찾아와서야 이런 사실을 알게 된 관람객들은 불만을 쏟아 내고 있다. 전문가들은 이런 전시 행태가 미술계 발전의 ( ) 수 있다고 우려한다. 전시회에 실망한 사람들이 미술에 대한 관심을 아예 끊을 수 있기 때문이다.', 'PUBLISHED', 'SOURCE_BOOK'),
  ('READING_21_22_SAMPLE_03', (select id from public.topik_sources where source_key = 'TOPIK_3_4_PHUONG_ANH_READING_20_21'), '21_22', 'SAMPLE', 82, '소방관은 재난 현장에서 끔찍한 상황을 자주 접하기 때문에 정신 건강에 위험이 따른다. 최근 이러한 문제가 심각해지자 인주시가 해결을 위해 ( ). 인주시는 빠른 시일 내에 정신 건강에 대해 조사를 실시하고 문제를 겪는 소방관이 있으면 전문 상담사를 보내 상담을 진행하기로 했다. 이와 더불어 심리 안정 프로그램 개발과 진료비 지원을 위한 예산을 확보했다고 발표했다.', 'PUBLISHED', 'SOURCE_BOOK'),
  ('READING_21_22_PRACTICE_01', (select id from public.topik_sources where source_key = 'TOPIK_3_4_PHUONG_ANH_READING_20_21'), '21_22', 'PRACTICE', 83, '아이가 어릴 때부터 외국어를 가르치는 부모들을 흔히 볼 수 있다. 이러한 부모의 높은 교육열은 장점도 있지만 지나치면 잃는 것이 더 많다. 계속 성장 중인 아이들은 신체뿐 아니라 두뇌도 점점 발달하기에 그에 맞게 교육을 하는 것이 좋다. 조기 교육은 일시적으로 우수한 학습 효과를 얻을 수도 있지만 쉽게 싫증을 내게 할 수도 있다. 따라서 아이들이 학습에서 ( ) 될 수도 있다. 똑똑한 아이로 키우고 싶다면 또래들과 자주 어울리게 하고 부모와 대화의 시간을 가지게 하는 것이 좋다. 그 과정을 통해 아이들은 생각하는 방법을 배우게 되고 두뇌도 발달하게 될 것이다.', 'PUBLISHED', 'SOURCE_BOOK'),
  ('READING_21_22_PRACTICE_02', (select id from public.topik_sources where source_key = 'TOPIK_3_4_PHUONG_ANH_READING_20_21'), '21_22', 'PRACTICE', 84, '노화는 질병이나 사고와 관계없이 시간의 흐름에 따라 신체 구조와 기능이 약해지는 것을 말한다. 이런 노화의 진행은 몸으로 느끼게 되는 것보다 일찍 시작되는데 30대쯤에는 근육의 양이 소실되기 시작하고 40세 전후로는 뇌의 부피가 10년마다 5% 정도씩 줄어든다. 하지만 신체 기관들 중에는 재생 능력이 뛰어나 젊음을 오래 유지하는 장기도 있다. 그중 ( ) 간은 스스로 기능을 되살리고 재생하는 능력이 뛰어나다. 수술로 부득이하게 간을 떼어 낸 경우에도 보통 반년 이내에 부피와 기능이 회복된다.', 'PUBLISHED', 'SOURCE_BOOK'),
  ('READING_21_22_PRACTICE_03', (select id from public.topik_sources where source_key = 'TOPIK_3_4_PHUONG_ANH_READING_20_21'), '21_22', 'PRACTICE', 85, '성공을 판단하는 기준은 무엇일까? 사람들은 보통 경제력과 사회적 지위로 성공 여부를 판단한다. 그런데 모든 사람들이 같은 능력과 가능성을 가지고 태어나는 것은 아니다. 어떤 사람은 6만큼의 능력과 가능성을 지니고 태어나지만 어떤 사람은 3만큼을 갖고 태어나기 때문이다. 그렇다면 3만큼의 능력으로 태어나서 6만큼을 이루는 것이 진정한 성공이 아닐까? 결국 성공은 타고난 자신과 발전한 자신 사이에서 이룬 성과라 할 수 있을 것이다. 따라서 성공은 자기 자신의 기준으로 판단하는 것이지 다른 사람의 ( ) 하는 것이 아니다.', 'PUBLISHED', 'SOURCE_BOOK'),
  ('READING_21_22_PRACTICE_04', (select id from public.topik_sources where source_key = 'TOPIK_3_4_PHUONG_ANH_READING_20_21'), '21_22', 'PRACTICE', 86, '정부가 공휴일을 확대하는 방안을 검토하고 있다. 이는 휴일을 늘려 국민들의 소비를 활성화하고 침체된 경기를 살리기 위해서이다. 하지만 물가가 오르고 가계 소득마저 줄어서 사람들이 ( ) 있는 상황에서 휴일이 늘어난다고 꼭 닫힌 지갑이 열릴지는 의문이다. 현재 가구당 소득은 역대 최저치를 기록했고 소비 지출도 올해 초부터 급감해서 소비가 살아나지 않고 있다.', 'PUBLISHED', 'SOURCE_BOOK'),
  ('READING_21_22_PRACTICE_05', (select id from public.topik_sources where source_key = 'TOPIK_3_4_PHUONG_ANH_READING_20_21'), '21_22', 'PRACTICE', 87, '골목은 집과 집, 길과 길을 이어주는 좁은 길로 누구나 자유롭게 오가며 이웃과 소통할 수 있는 공간이다. 그러나 도시화로 인해서 골목은 아파트나 주차장 등 다른 공간으로 대체되어 점점 사라지고 있다. 골목을 잃어간다는 것은 다른 사람과 소통하고 나눌 수 있는 공간을 잃고 있다는 뜻이다. 최근 이를 안타깝게 여기던 젊은 건축가들이 ( ) 사라지고 있는 골목과 골목 문화를 복원하기 위해서 애쓰고 있다. 젊은 건축가들은 정부와 지역 주민들과 협력해서 오래되고 낡은 환경의 골목을 안전하고 쾌적한 환경으로 바꾸고 있을 뿐만 아니라 지역의 역사와 전통을 반영한 특색이 있는 골목길로 재탄생시키고 있다.', 'PUBLISHED', 'SOURCE_BOOK')
on conflict (source_key) do update set source_id = excluded.source_id, question_pair = excluded.question_pair, set_type = excluded.set_type, source_page = excluded.source_page, passage_ko = excluded.passage_ko, status = excluded.status, source_type = excluded.source_type;

insert into public.topik_reading_mc_questions(exercise_id, question_no, skill_code, prompt_ko, options, answer_index, correct_idiom_id, option_idiom_ids) values
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_19_20_SAMPLE_01'), 19, 'CONNECTIVE_IN_CONTEXT', null, '["결코","특히","비록","반면"]'::jsonb, 4, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_19_20_SAMPLE_01'), 20, 'TOPIC_MAIN_IDEA', '윗글의 주제로 가장 알맞은 것을 고르십시오.', '["질문을 한 후에 생각할 시간을 줘야 한다.","도움이 되는 답을 얻으려면 질문을 잘해야 한다.","질문하기 전에 예상되는 답을 미리 생각해야 한다.","추상적인 질문으로 자유로운 생각을 끌어내야 한다."]'::jsonb, 2, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_19_20_SAMPLE_02'), 19, 'CONNECTIVE_IN_CONTEXT', null, '["혹시","또는","비록","만약"]'::jsonb, 3, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_19_20_SAMPLE_02'), 20, 'TOPIC_MAIN_IDEA', '윗글의 주제로 가장 알맞은 것을 고르십시오.', '["황제펭귄은 서로 도우면서 추위에 맞서 생존해 왔다.","황제펭귄은 둥글게 둘러서 날씨에 대한 정보를 알린다.","황제펭귄은 추위에서 살아남기 위해 움직임이 느려졌다.","황제펭귄은 무리 생활을 통해 경쟁에서 이기는 법을 배운다."]'::jsonb, 1, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_19_20_SAMPLE_03'), 19, 'CONNECTIVE_IN_CONTEXT', null, '["과연","비록","차라리","오히려"]'::jsonb, 4, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_19_20_SAMPLE_03'), 20, 'TOPIC_MAIN_IDEA', '윗글의 주제로 가장 알맞은 것을 고르십시오.', '["마케팅도 중요하지만 제품의 품질이 더 중요하다.","식품 기업은 먼저 소비자의 요구를 확인해야 한다.","제품에 재미 요소를 포함하는 마케팅 전략이 필요하다.","특이한 제품보다 소비자에게 익숙한 것이 홍보에 더 좋다."]'::jsonb, 1, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_19_20_PRACTICE_01'), 19, 'CONNECTIVE_IN_CONTEXT', null, '["가끔","역시","비록","전혀"]'::jsonb, 4, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_19_20_PRACTICE_01'), 20, 'TOPIC_MAIN_IDEA', '윗글의 주제로 가장 알맞은 것을 고르십시오.', '["달걀은 겉에 빛이 나면 오래된 것이다.","달걀은 신선할수록 물에 뜨는 특성이 있다.","달걀은 많이 먹을수록 심장의 기능이 좋아진다.","달걀이 건강에 좋지 않다고 생각하는 사람들이 있다."]'::jsonb, 4, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_19_20_PRACTICE_02'), 19, 'CONNECTIVE_IN_CONTEXT', null, '["그러면","그리고","오히려","그러나"]'::jsonb, 4, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_19_20_PRACTICE_02'), 20, 'TOPIC_MAIN_IDEA', '윗글의 주제로 가장 알맞은 것을 고르십시오.', '["우리는 자존감을 가지고 살아야 한다.","자존감은 상대적 박탈감을 느끼게 한다.","만족함을 알 때 감사하는 삶을 살 수 있다.","가족과 친구로 인해 불편을 이겨낼 수 있다."]'::jsonb, 3, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_19_20_PRACTICE_03'), 19, 'CONNECTIVE_IN_CONTEXT', null, '["그렇지 않으면","그렇지 않아도","그렇기 때문에","그렇기는 하지만"]'::jsonb, 1, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_19_20_PRACTICE_03'), 20, 'TOPIC_MAIN_IDEA', '윗글의 주제로 가장 알맞은 것을 고르십시오.', '["부모는 항상 아이와 같이 걸어야 한다.","아이가 크더라도 스스로 판단하는 것은 어렵다.","부모는 아이가 크면 선택의 자유를 주어야 한다.","부모가 선택을 해 주는 것이 아이의 성장을 돕는다."]'::jsonb, 3, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_19_20_PRACTICE_04'), 19, 'CONNECTIVE_IN_CONTEXT', null, '["역시","아마","오히려","반드시"]'::jsonb, 3, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_19_20_PRACTICE_04'), 20, 'TOPIC_MAIN_IDEA', '윗글의 주제로 가장 알맞은 것을 고르십시오.', '["도시에 건설하는 실버타운이 많아지고 있다.","자녀들과 함께 살고 싶어 하는 노인이 증가하였다.","요즘 노인들은 은퇴 후에 시골에 살고 싶어 한다.","최근 가격이 저렴한 실버타운이 큰 인기를 얻고 있다."]'::jsonb, 1, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_19_20_PRACTICE_05'), 19, 'CONNECTIVE_IN_CONTEXT', null, '["만약","또는","역시","물론"]'::jsonb, 1, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_19_20_PRACTICE_05'), 20, 'TOPIC_MAIN_IDEA', '윗글의 주제로 가장 알맞은 것을 고르십시오.', '["새집 증후군은 더러운 집으로 이사하면 생긴다.","새집 증후군이 발생하면 이상한 증상이 나타난다.","새집 증후군이 생기면 건축자재를 바꾸는 것이 좋다.","새집 증후군이 있으면 공기를 깨끗이 해주어야 한다."]'::jsonb, 4, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_21_22_SAMPLE_01'), 21, 'CONTENT_MATCH', null, '["눈을 딱 감고","머리를 맞대고","손에 땀을 쥐고","목에 힘을 주고"]'::jsonb, 2, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_21_22_SAMPLE_01'), 22, 'IDIOM_IN_CONTEXT', '윗글의 내용과 같은 것을 고르십시오.', '["이 초등학교는 기업에 요청해 악기 전문가를 구했다.","이 초등학교는 선생님들의 노력에도 학생 수가 줄었다.","이 초등학교에서 개최한 음악회에 유명 음악가가 참여했다.","이 초등학교 선생님들이 학생들에게 직접 악기를 가르쳤다."]'::jsonb, 3, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_21_22_SAMPLE_02'), 21, 'CONTENT_MATCH', null, '["입맛에 맞을","가슴을 울릴","발목을 잡을","손을 맞잡을"]'::jsonb, 3, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_21_22_SAMPLE_02'), 22, 'IDIOM_IN_CONTEXT', '윗글의 내용과 같은 것을 고르십시오.', '["복제품 전시회는 입장료를 받지 않는다.","최근 미술 전시회를 찾는 사람들이 많지 않다.","전시회에서 복제품을 전시하는 일이 점점 줄고 있다.","복제품 전시회인지 모르고 전시회를 방문한 관람객들이 있다."]'::jsonb, 4, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_21_22_SAMPLE_03'), 21, 'CONTENT_MATCH', null, '["등 떠밀었다","눈을 맞췄다","발 벗고 나섰다","손에 땀을 쥐었다"]'::jsonb, 3, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_21_22_SAMPLE_03'), 22, 'IDIOM_IN_CONTEXT', '윗글의 내용과 같은 것을 고르십시오.', '["소방관의 심리적 어려움은 최근 많이 해소되었다.","인주시는 소방관의 정신 건강 조사를 모두 마쳤다.","인주시는 소방관 심리 안정 프로그램을 운영할 계획이다.","소방관이 정신 건강 상담을 받으려면 상담사를 찾아가야 한다."]'::jsonb, 3, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_21_22_PRACTICE_01'), 21, 'CONTENT_MATCH', null, '["맛을 보게","손을 떼게","열을 올리게","문을 두드리게"]'::jsonb, 2, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_21_22_PRACTICE_01'), 22, 'IDIOM_IN_CONTEXT', '윗글의 내용과 같은 것을 고르십시오.', '["조기 교육의 단점보다는 장점을 살려야 한다.","외국어 교육으로 인한 부작용을 고려해야 한다.","부모의 교육에 대한 열정을 높이 평가해야 한다.","아이들에게는 발달 단계에 맞는 교육을 해야 한다."]'::jsonb, 4, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_21_22_PRACTICE_02'), 21, 'CONTENT_MATCH', null, '["손에 잡히는","손에 꼽히는","눈에 걸리는","눈에 밟히는"]'::jsonb, 2, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_21_22_PRACTICE_02'), 22, 'IDIOM_IN_CONTEXT', '윗글의 내용과 같은 것을 고르십시오.', '["뇌는 30대부터 작아진다.","간은 떼어 내도 다시 커진다.","신체 노화는 40대 이후 시작된다.","노화는 병으로 건강을 잃는 것을 뜻한다."]'::jsonb, 2, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_21_22_PRACTICE_03'), 21, 'CONTENT_MATCH', null, '["손에 익어야","발이 넓어야","눈길을 끌어야","눈높이에 맞아야"]'::jsonb, 4, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_21_22_PRACTICE_03'), 22, 'IDIOM_IN_CONTEXT', '윗글의 내용과 같은 것을 고르십시오.', '["사람들은 동일한 능력을 갖고 태어난다.","성공에 대한 가능성을 경제력으로 알 수 있다.","성공 여부를 판단할 수 있는 공통의 기준이 있다.","타고난 능력과 이루어낸 능력의 차이가 성공의 크기다."]'::jsonb, 4, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_21_22_PRACTICE_04'), 21, 'CONTENT_MATCH', null, '["손을 떼고","등을 돌리고","발뺌을 하고","허리띠를 졸라매고"]'::jsonb, 4, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_21_22_PRACTICE_04'), 22, 'IDIOM_IN_CONTEXT', '윗글의 내용과 같은 것을 고르십시오.', '["침체된 경기를 살리기 위해 물가를 인하했다.","올해 초부터 소비 지출이 점차 늘어나고 있다.","공휴일 확대가 소비 활성화로 이어질지는 알 수 없다.","현재 공휴일이 많아서 정부가 공휴일 축소를 검토하고 있다."]'::jsonb, 3, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_21_22_PRACTICE_05'), 21, 'CONTENT_MATCH', null, '["한 우물을 파서","발 벗고 나서서","귓등으로 들어서","찬물을 끼얹어서"]'::jsonb, 2, null, array[]::uuid[]),
  ((select id from public.topik_reading_20_21_exercises where source_key = 'READING_21_22_PRACTICE_05'), 22, 'IDIOM_IN_CONTEXT', '윗글의 내용과 같은 것을 고르십시오.', '["도시화 때문에 골목이 점점 늘어나고 있다.","정부와 지역 주민들은 골목길 복원에 반대한다.","골목이 사라지면 사람들끼리 소통하기 쉬워질 것이다.","젊은 건축가들은 골목을 재생시키려고 노력하고 있다."]'::jsonb, 4, null, array[]::uuid[])
on conflict (exercise_id, question_no) do update set skill_code = excluded.skill_code, prompt_ko = excluded.prompt_ko, options = excluded.options, answer_index = excluded.answer_index, correct_idiom_id = excluded.correct_idiom_id, option_idiom_ids = excluded.option_idiom_ids;

do $$
declare group_count integer; idiom_count integer; s_count integer; a_count integer; b_count integer; gloss_count integer; review_count integer; q20_set_count integer; q21_set_count integer; invalid_question_count integer;
begin
  select count(*) into group_count from public.topik_reading_idiom_groups;
  select count(*) into idiom_count from public.topik_reading_idioms where source_type = 'SOURCE_BOOK';
  select count(*) filter (where priority = 'S'), count(*) filter (where priority = 'A'), count(*) filter (where priority = 'B'), count(*) filter (where review_status = 'NEEDS_GLOSS'), count(*) filter (where review_status = 'NEEDS_REVIEW') into s_count, a_count, b_count, gloss_count, review_count from public.topik_reading_idioms where source_type = 'SOURCE_BOOK';
  select count(*) into q20_set_count from public.topik_reading_20_21_exercises where question_pair = '19_20' and source_type = 'SOURCE_BOOK';
  select count(*) into q21_set_count from public.topik_reading_20_21_exercises where question_pair = '21_22' and source_type = 'SOURCE_BOOK';
  select count(*) into invalid_question_count from public.topik_reading_mc_questions where jsonb_array_length(options) <> 4 or answer_index not between 1 and 4;
  if group_count <> 11 or idiom_count <> 88 or s_count <> 7 or a_count <> 22 or b_count <> 59 or gloss_count <> 13 or review_count <> 1 or q20_set_count <> 8 or q21_set_count <> 8 or invalid_question_count <> 0 then raise exception 'TOPIK Reading 20-21 seed validation failed: groups %, idioms %, S/A/B %/%/%, gloss %, review %, Q20 %, Q21 %, invalid questions %', group_count, idiom_count, s_count, a_count, b_count, gloss_count, review_count, q20_set_count, q21_set_count, invalid_question_count; end if;
end $$;
commit;
