import { AlertTriangle, CheckCircle2, Lightbulb, RefreshCw } from 'lucide-react';
import { Link } from 'react-router-dom';
import type { Q54DraftAssessment, Q54Requirement } from '../types';

type Props = { assessment: Q54DraftAssessment; requirements: Q54Requirement[]; draftId: string };
const coverageLabel = { COVERED: 'Đã trả lời', PARTIAL: 'Chưa đủ', MISSING: 'Chưa trả lời' };

export function DraftAssessmentPanel({ assessment, requirements, draftId }: Props) {
  const requirementById = new Map(requirements.map((requirement) => [requirement.id, requirement]));
  return <section className="mt-7 border border-slate-200 bg-white p-5 sm:p-6">
    <div className="flex items-start gap-3"><CheckCircle2 className={`mt-0.5 h-5 w-5 ${assessment.verdict === 'ACCEPTABLE' ? 'text-emerald-600' : 'text-amber-600'}`} /><div><h2 className="font-bold text-slate-900">AI feedback theo rubric</h2><p className="mt-1 text-sm text-slate-600">{assessment.summaryVi}</p></div></div>
    <div className="mt-6"><h3 className="text-sm font-bold text-slate-800">Requirement coverage</h3><div className="mt-3 space-y-2">{assessment.requirements.map((item) => <article key={item.requirementId} className="border-l-2 border-slate-200 px-3 py-2"><div className="flex flex-wrap items-center gap-2"><p className="font-medium text-slate-900">{requirementById.get(item.requirementId)?.label_vi || 'Requirement'}</p><span className={`rounded-md px-2 py-0.5 text-xs font-bold ${item.status === 'COVERED' ? 'bg-emerald-100 text-emerald-800' : item.status === 'PARTIAL' ? 'bg-amber-100 text-amber-800' : 'bg-rose-100 text-rose-800'}`}>{coverageLabel[item.status]}</span></div>{item.evidenceKo && <p lang="ko" className="mt-1 text-sm text-slate-700">{item.evidenceKo}</p>}<p className="mt-1 text-sm text-slate-500">{item.suggestionVi}</p></article>)}</div></div>
    <div className="mt-6 grid gap-4 md:grid-cols-2"><article className="border-l-2 border-sky-500 bg-sky-50/40 p-3"><p className="text-xs font-bold uppercase tracking-wider text-sky-800">Logic</p><p className="mt-1 text-sm text-slate-700">{assessment.logic.messageVi}</p></article><article className="border-l-2 border-violet-500 bg-violet-50/40 p-3"><p className="text-xs font-bold uppercase tracking-wider text-violet-800">Cohesion & style</p><p className="mt-1 text-sm text-slate-700">{assessment.cohesion.messageVi} {assessment.formalStyle.messageVi}</p></article></div>
    {assessment.collocations.length > 0 && <div className="mt-6"><h3 className="text-sm font-bold text-slate-800">Collocation</h3><div className="mt-2 space-y-2">{assessment.collocations.map((item, index) => <p key={`${item.expression}-${index}`} className="text-sm text-slate-700"><span lang="ko" className="font-semibold">{item.expression}</span> → <span lang="ko" className="font-semibold text-emerald-700">{item.suggestion}</span><span className="text-slate-500"> · {item.explanationVi}</span></p>)}</div></div>}
    {assessment.repetition.length > 0 && <div className="mt-6"><h3 className="text-sm font-bold text-slate-800">Repetition detector</h3>{assessment.repetition.map((item) => <p key={item.expression} className="mt-2 text-sm text-slate-700"><span lang="ko" className="font-semibold">{item.expression}</span> × {item.count}{item.alternatives.length > 0 && <span className="text-slate-500"> · thử: {item.alternatives.join(', ')}</span>}</p>)}</div>}
    {assessment.errors.length > 0 && <div className="mt-6"><h3 className="flex items-center gap-2 text-sm font-bold text-slate-800"><AlertTriangle className="h-4 w-4 text-rose-600" />Điểm cần sửa</h3><div className="mt-2 space-y-3">{assessment.errors.map((item, index) => <article key={`${item.original}-${index}`} className="border border-rose-100 bg-rose-50/30 p-3"><p lang="ko" className="text-sm text-rose-800">{item.original}</p><p lang="ko" className="mt-1 text-sm font-semibold text-emerald-800">{item.corrected}</p><p className="mt-1 text-sm text-slate-600">{item.explanationVi}</p></article>)}</div></div>}
    {assessment.rewriteFocus.length > 0 && <div className="mt-6 flex items-start gap-2 border-l-2 border-amber-400 bg-amber-50/50 p-3"><Lightbulb className="mt-0.5 h-4 w-4 text-amber-700" /><div><p className="text-sm font-bold text-amber-900">Trọng tâm bản tiếp theo</p><ul className="mt-1 space-y-1 text-sm text-slate-700">{assessment.rewriteFocus.map((focus) => <li key={focus}>{focus}</li>)}</ul></div></div>}
    <Link to={`/topik/writing/54/lab/review/${draftId}`} className="mt-6 inline-flex items-center gap-2 rounded-lg bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white"><RefreshCw className="h-4 w-4" />Viết Draft 2</Link>
  </section>;
}
