import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Clock3, Loader2 } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { useAuth } from '../../../contexts/AuthContext';
import { getQ54Service } from '../service';
import { getQ54TrainingService } from '../training';
import { TrainingPageHeader } from '../components/TrainingPageHeader';
import type { Q54QuestionBundle, Q54TrainingSession } from '../types';

export function Q54IdeaSprintPage() {
  const { sessionId = '' } = useParams(); const { isDemo } = useAuth(); const navigate = useNavigate(); const contentService = useMemo(() => getQ54Service(isDemo), [isDemo]); const trainingService = useMemo(() => getQ54TrainingService(isDemo), [isDemo]);
  const [session, setSession] = useState<Q54TrainingSession | null>(null); const [bundle, setBundle] = useState<Q54QuestionBundle | null>(null); const [requirementId, setRequirementId] = useState(''); const [ideas, setIdeas] = useState(['', '', '']); const [remaining, setRemaining] = useState(60); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { void trainingService.getSession(sessionId).then(async (current) => { setSession(current); const data = await contentService.getQuestionBundle(current.question_id); setBundle(data); setRequirementId(data.requirements[0]?.id || ''); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Không thể tải Idea Sprint.')); }, [contentService, sessionId, trainingService]);
  useEffect(() => { if (!session || remaining <= 0) return; const timer = window.setInterval(() => setRemaining((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [remaining, session]);
  const finish = async (skipped: boolean) => { if (!session || !requirementId || saving) return; try { setSaving(true); await trainingService.recordIdeaSprint({ sessionId: session.id, requirementId, ideas: skipped ? [] : ideas.map((idea) => idea.trim()).filter(Boolean), durationMs: (60 - remaining) * 1000, skipped }); await trainingService.advanceBankStage(session.id, 'IDEA'); navigate(`/topik/writing/54/lab/sessions/${session.id}/logic`); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Không thể lưu Idea Sprint.'); } finally { setSaving(false); } };
  if (error) return <div className="mx-auto max-w-xl px-4 py-14 text-center text-rose-700">{error}</div>; if (!session || !bundle) return <div className="flex min-h-[60vh] items-center justify-center gap-3 text-slate-500"><Loader2 className="h-6 w-6 animate-spin" />Đang tải...</div>;
  const requirement = bundle.requirements.find((item) => item.id === requirementId) || bundle.requirements[0];
  return <div className="mx-auto max-w-3xl px-4 py-8 sm:px-6"><TrainingPageHeader session={session} title="Idea Sprint" subtitle="Tự nghĩ ý trước khi mở Idea Bank." /><section className="mt-8 border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><label className="text-sm font-semibold text-slate-700">Requirement<select value={requirementId} onChange={(event) => setRequirementId(event.target.value)} className="ml-3 rounded-md border border-slate-200 bg-white px-2 py-1 text-sm">{bundle.requirements.map((item) => <option key={item.id} value={item.id}>{item.label_vi}</option>)}</select></label><span className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 font-bold ${remaining === 0 ? 'bg-rose-100 text-rose-800' : 'bg-brand-50 text-brand-800'}`}><Clock3 className="h-4 w-4" />{remaining}s</span></div><p lang="ko" className="mt-5 text-lg font-bold text-slate-900">{requirement?.prompt_ko}</p><p className="mt-2 text-sm text-slate-600">Ghi tối đa ba ý ngắn bằng tiếng Hàn hoặc tiếng Việt. Chưa có gợi ý nào được mở ở bước này.</p><div className="mt-5 space-y-3">{ideas.map((idea, index) => <input key={index} value={idea} disabled={remaining === 0} onChange={(event) => setIdeas((current) => current.map((value, itemIndex) => itemIndex === index ? event.target.value : value))} placeholder={`Ý ${index + 1}`} className="w-full rounded-lg border border-slate-200 px-3 py-3 text-sm focus:border-brand-500 focus:outline-none focus:ring-2 focus:ring-brand-500/20" />)}</div><div className="mt-6 flex flex-wrap gap-3"><button type="button" onClick={() => void finish(false)} disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60"><ArrowRight className="h-4 w-4" />{saving ? 'Đang lưu...' : remaining === 0 ? 'Xem Idea Bank' : 'Hoàn thành sớm'}</button><button type="button" onClick={() => void finish(true)} disabled={saving} className="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700">Bỏ qua và mở Bank</button></div></section></div>;
}
