import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, CheckCircle2, Loader2, RotateCcw } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { useAuth } from '../../../contexts/AuthContext';
import { TrainingPageHeader } from '../components/TrainingPageHeader';
import { getIdeasForRequirement } from '../ideaBank';
import { getQ54Service } from '../service';
import { getQ54TrainingService } from '../training';
import type { Q54Idea, Q54QuestionBundle, Q54TrainingSession } from '../types';

function shuffled(values: string[]) { return [...values].sort(() => Math.random() - 0.5); }

export function Q54LogicChainPage() {
  const { sessionId = '' } = useParams(); const { isDemo } = useAuth(); const navigate = useNavigate(); const contentService = useMemo(() => getQ54Service(isDemo), [isDemo]); const trainingService = useMemo(() => getQ54TrainingService(isDemo), [isDemo]);
  const [session, setSession] = useState<Q54TrainingSession | null>(null); const [bundle, setBundle] = useState<Q54QuestionBundle | null>(null); const [idea, setIdea] = useState<Q54Idea | null>(null); const [nodes, setNodes] = useState<string[]>([]); const [startedAt, setStartedAt] = useState(() => Date.now()); const [result, setResult] = useState<{ correct: boolean; expected: string[] } | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void trainingService.getSession(sessionId).then(async (current) => { setSession(current); const data = await contentService.getQuestionBundle(current.question_id); setBundle(data); const requirement = data.requirements[0]; const firstIdea = requirement ? getIdeasForRequirement(data.ideas, data.topic.id, requirement)[0] : null; if (!firstIdea) throw new Error('Chưa có logic chain phù hợp cho đề này.'); setIdea(firstIdea); setNodes(shuffled(firstIdea.logic_chain_ko?.length ? firstIdea.logic_chain_ko : firstIdea.logic_steps)); setStartedAt(Date.now()); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Không thể tải Logic Chain.')); }, [contentService, sessionId, trainingService]);
  const move = (index: number, direction: -1 | 1) => setNodes((current) => { const target = index + direction; if (target < 0 || target >= current.length) return current; const next = [...current]; [next[index], next[target]] = [next[target], next[index]]; return next; });
  const check = async () => { if (!session || !idea || result) return; try { setResult(await trainingService.recordLogicChain({ sessionId: session.id, ideaId: idea.id, orderedNodes: nodes, durationMs: Date.now() - startedAt })); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Không thể kiểm tra logic.'); } };
  if (error) return <div className="mx-auto max-w-xl px-4 py-14 text-center text-rose-700">{error}</div>; if (!session || !bundle || !idea) return <div className="flex min-h-[60vh] items-center justify-center gap-3 text-slate-500"><Loader2 className="h-6 w-6 animate-spin" />Đang tải...</div>;
  return <div className="mx-auto max-w-3xl px-4 py-8 sm:px-6"><TrainingPageHeader session={session} title="Logic Chain Builder" subtitle="Xếp các mắt xích để biến ý thành một lập luận rõ ràng." /><section className="mt-8 border border-slate-200 bg-white p-5 sm:p-6"><p lang="ko" className="text-lg font-bold text-slate-900">{idea.keyword_ko}</p><p className="mt-1 text-sm text-slate-600">{idea.keyword_vi}</p><div className="mt-6 space-y-2">{nodes.map((node, index) => <div key={`${node}-${index}`} className="flex items-center gap-3 border border-slate-200 bg-slate-50 p-3"><span className="w-6 text-sm font-bold text-slate-400">{index + 1}</span><p lang="ko" className="flex-1 font-medium text-slate-800">{node}</p><div className="flex gap-1"><button type="button" title="Đưa lên" onClick={() => move(index, -1)} className="rounded-md border border-slate-200 p-1.5 text-slate-600 disabled:opacity-30" disabled={index === 0 || !!result}>↑</button><button type="button" title="Đưa xuống" onClick={() => move(index, 1)} className="rounded-md border border-slate-200 p-1.5 text-slate-600 disabled:opacity-30" disabled={index === nodes.length - 1 || !!result}>↓</button></div></div>)}</div>{result && <div className={`mt-5 border-l-2 p-3 ${result.correct ? 'border-emerald-500 bg-emerald-50' : 'border-amber-500 bg-amber-50'}`}><div className="flex items-center gap-2 font-bold text-slate-800">{result.correct ? <CheckCircle2 className="h-5 w-5 text-emerald-600" /> : <RotateCcw className="h-5 w-5 text-amber-600" />}{result.correct ? 'Logic chính xác' : 'Thử đối chiếu lại chain'}</div>{!result.correct && <p lang="ko" className="mt-2 text-sm text-slate-700">{result.expected.join(' → ')}</p>}</div>}<div className="mt-6 flex gap-3"><button type="button" onClick={() => void check()} disabled={!!result} className="rounded-lg bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">Kiểm tra chain</button>{result && <button type="button" onClick={() => navigate(`/topik/writing/54/lab/sessions/${session.id}/sentence`)} className="inline-flex items-center gap-2 rounded-lg border border-brand-200 bg-brand-50 px-4 py-2.5 text-sm font-semibold text-brand-700">Sentence Builder <ArrowRight className="h-4 w-4" /></button>}</div></section></div>;
}
