import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Loader2, Save } from 'lucide-react';
import { useParams } from 'react-router-dom';
import { useAuth } from '../../../contexts/AuthContext';
import { DraftAssessmentPanel } from '../components/DraftAssessmentPanel';
import { getQ54Service } from '../service';
import { getQ54TrainingService } from '../training';
import type { Q54DraftAssessment, Q54QuestionBundle, Q54WritingDraft } from '../types';

export function Q54ReviewPage() {
  const { draftId = '' } = useParams(); const { isDemo } = useAuth(); const contentService = useMemo(() => getQ54Service(isDemo), [isDemo]); const trainingService = useMemo(() => getQ54TrainingService(isDemo), [isDemo]); const [draft, setDraft] = useState<Q54WritingDraft | null>(null); const [bundle, setBundle] = useState<Q54QuestionBundle | null>(null); const [content, setContent] = useState(''); const [next, setNext] = useState<{ id: string; assessment: Q54DraftAssessment } | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void trainingService.getDraft(draftId).then(async (current) => { setDraft(current); setContent(current.content_ko); setBundle(await contentService.getQuestionBundle(current.question_id)); }).catch((value: unknown) => setError(value instanceof Error ? value.message : 'Không thể tải Draft.')); }, [contentService, draftId, trainingService]);
  const submit = async () => { if (!draft || saving || !content.trim()) return; try { setSaving(true); const response = await trainingService.assessDraft({ submissionId: crypto.randomUUID(), sessionId: draft.session_id, questionId: draft.question_id, requirementId: draft.requirement_id, ideaId: draft.idea_id, unitType: draft.unit_type, contentKo: content, parentDraftId: draft.id, assistanceStage: draft.assistance_stage }); if (response.assessment) setNext({ id: response.draftId, assessment: response.assessment }); } catch (value) { setError(value instanceof Error ? value.message : 'Không thể lưu Draft 2.'); } finally { setSaving(false); } };
  if (error) return <div className="mx-auto max-w-xl px-4 py-14 text-center text-rose-700">{error}</div>; if (!draft || !bundle) return <div className="flex min-h-[60vh] items-center justify-center gap-3 text-slate-500"><Loader2 className="h-6 w-6 animate-spin" />Đang tải Draft...</div>;
  return <div className="mx-auto max-w-5xl px-4 py-8 sm:px-6"><p className="text-xs font-bold uppercase tracking-wider text-brand-700">Review & Rewrite</p><h1 className="mt-1 text-2xl font-extrabold text-slate-900">Draft {draft.draft_number + 1}</h1><p className="mt-1 text-sm text-slate-600">Tự sửa từ Draft trước; hệ thống không chèn bài mẫu thay cho bạn.</p><div className="mt-7 grid gap-6 lg:grid-cols-2"><section className="border border-slate-200 bg-slate-50 p-5"><h2 className="font-bold">Draft {draft.draft_number}</h2><pre className="mt-3 whitespace-pre-wrap font-sans text-sm leading-7 text-slate-700">{draft.content_ko}</pre>{draft.assessment_json && <div className="mt-6 border-t border-slate-200 pt-5"><p className="font-bold text-slate-800">Feedback trước đó</p><p className="mt-2 text-sm text-slate-600">{draft.assessment_json.summaryVi}</p></div>}</section><section className="border border-slate-200 bg-white p-5"><label className="text-sm font-bold text-slate-800">Bản viết lại<textarea value={content} onChange={(event) => setContent(event.target.value)} className="mt-3 min-h-80 w-full rounded-lg border border-slate-200 p-3 text-sm leading-7" /></label><button type="button" onClick={() => void submit()} disabled={saving || !content.trim()} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60"><Save className="h-4 w-4" />{saving ? 'Đang chấm...' : 'Nộp Draft 2'}</button>{error && <p className="mt-3 text-sm text-rose-700">{error}</p>}</section></div>{next && <DraftAssessmentPanel assessment={next.assessment} requirements={bundle.requirements} draftId={next.id} />}<p className="mt-6 inline-flex items-center gap-2 text-sm text-slate-500">So sánh Draft 1 và Draft 2 nằm cạnh nhau để bạn thấy thay đổi thực tế. <ArrowRight className="h-4 w-4" /></p></div>;
}
