import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Loader2, PenLine } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { useAuth } from '../../../contexts/AuthContext';
import { getQ54Service } from '../service';
import { getQ54TrainingService } from '../training';
import type { Q54UserError } from '../types';

export function Q54RewritePage() {
  const { errorId = '' } = useParams(); const { isDemo } = useAuth(); const contentService = useMemo(() => getQ54Service(isDemo), [isDemo]); const trainingService = useMemo(() => getQ54TrainingService(isDemo), [isDemo]); const [item, setItem] = useState<Q54UserError | null>(null); const [answer, setAnswer] = useState(''); const [result, setResult] = useState<{ correct: boolean; mastered: boolean; successDays: number } | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void contentService.getErrors('').then((items) => { const selected = items.find((value) => value.id === errorId); if (!selected) throw new Error('Không tìm thấy lỗi này.'); setItem(selected); }).catch((value: unknown) => setError(value instanceof Error ? value.message : 'Không thể tải Rewrite Challenge.')); }, [contentService, errorId]);
  const submit = async () => { if (!item || !answer.trim()) return; try { setResult(await trainingService.recordRewrite(item.id, answer)); } catch (value) { setError(value instanceof Error ? value.message : 'Không thể kiểm tra câu viết lại.'); } };
  if (error) return <div className="mx-auto max-w-xl px-4 py-14 text-center text-rose-700">{error}</div>; if (!item) return <div className="flex min-h-[60vh] items-center justify-center gap-3 text-slate-500"><Loader2 className="h-6 w-6 animate-spin" />Đang tải...</div>;
  return <div className="mx-auto max-w-2xl px-4 py-8 sm:px-6"><Link to="/topik/writing/54/lab/drills" className="text-sm font-semibold text-slate-500 hover:text-slate-900">← Error Training</Link><section className="mt-6 border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-center gap-2"><PenLine className="h-5 w-5 text-brand-600" /><h1 className="text-xl font-extrabold">Rewrite Challenge</h1></div><p className="mt-4 text-sm text-slate-600">Hãy tự viết lại cách diễn đạt tự nhiên hơn. Đáp án được giữ ẩn trong bước này.</p><p lang="ko" className="mt-5 border-l-2 border-rose-400 bg-rose-50 px-3 py-2 font-semibold text-rose-800">{item.original_text}</p><p className="mt-3 text-sm text-slate-600">{item.explanation_vi}</p><textarea value={answer} onChange={(event) => setAnswer(event.target.value)} className="mt-5 min-h-28 w-full rounded-lg border border-slate-200 p-3 text-sm" placeholder="Viết lại bằng tiếng Hàn" /><button type="button" onClick={() => void submit()} className="mt-4 rounded-lg bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white">Kiểm tra</button>{result && <div className={`mt-5 border-l-2 p-3 ${result.correct ? 'border-emerald-500 bg-emerald-50' : 'border-amber-500 bg-amber-50'}`}><p className="flex items-center gap-2 font-bold text-slate-800">{result.correct && <CheckCircle2 className="h-5 w-5 text-emerald-600" />}{result.correct ? 'Đúng rồi' : 'Chưa khớp, hãy thử lại sau khi xem feedback.'}</p><p className="mt-1 text-sm text-slate-600">Đúng ở {result.successDays}/3 ngày khác nhau.{result.mastered && ' Lỗi này đã được mastered.'}</p></div>}</section></div>;
}
