import { useEffect, useMemo, useState } from 'react';
import { BarChart3, Loader2, Target } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../../contexts/AuthContext';
import { getQ54TrainingService } from '../training';
import type { Q54UserError, Q54WritingDraft } from '../types';

export function Q54WeaknessPage() {
  const { isDemo } = useAuth(); const trainingService = useMemo(() => getQ54TrainingService(isDemo), [isDemo]); const [data, setData] = useState<{ essayCount: number; eligible: boolean; errors: Q54UserError[]; drafts: Q54WritingDraft[] } | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void trainingService.getWeakness().then(setData).catch((value: unknown) => setError(value instanceof Error ? value.message : 'Không thể tải Weakness Dashboard.')); }, [trainingService]);
  if (error) return <div className="mx-auto max-w-xl px-4 py-14 text-center text-rose-700">{error}</div>; if (!data) return <div className="flex min-h-[60vh] items-center justify-center gap-3 text-slate-500"><Loader2 className="h-6 w-6 animate-spin" />Đang tổng hợp tiến độ...</div>;
  const grouped = data.errors.reduce<Record<string, number>>((current, item) => ({ ...current, [item.error_type]: (current[item.error_type] || 0) + item.occurrence_count }), {});
  return <div className="mx-auto max-w-4xl px-4 py-8 sm:px-6"><Link to="/topik/writing/54" className="text-sm font-semibold text-slate-500 hover:text-slate-900">← TOPIK Writing 54</Link><div className="mt-5 flex items-center gap-3"><BarChart3 className="h-7 w-7 text-brand-600" /><div><h1 className="text-2xl font-extrabold text-slate-900">Personal Weakness Dashboard</h1><p className="mt-1 text-sm text-slate-600">Tổng hợp lỗi từ các bài Q54 đã được AI assessment.</p></div></div><section className="mt-8 border border-slate-200 bg-white p-5"><p className="text-sm text-slate-600">Full Essay đã chấm</p><p className="mt-1 text-3xl font-extrabold text-slate-900">{data.essayCount}/20</p>{!data.eligible && <p className="mt-2 text-sm text-amber-700">Dashboard đầy đủ sẽ mở sau 20 Full Essay. Hiện vẫn hiển thị lỗi đã tích lũy.</p>}{data.eligible && <Link to="/topik/writing/54/lab/drills" className="mt-4 inline-flex items-center gap-2 rounded-lg bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white"><Target className="h-4 w-4" />Luyện điểm yếu hôm nay</Link>}</section><div className="mt-6 grid gap-4 md:grid-cols-2"><section className="border border-slate-200 bg-white p-5"><h2 className="font-bold">Lỗi theo loại</h2>{Object.entries(grouped).length ? <div className="mt-4 space-y-3">{Object.entries(grouped).sort((a, b) => b[1] - a[1]).map(([type, count]) => <div key={type} className="flex justify-between border-b border-slate-100 pb-2 text-sm"><span>{type}</span><span className="font-bold text-rose-700">{count}</span></div>)}</div> : <p className="mt-3 text-sm text-slate-500">Chưa có lỗi được aggregate.</p>}</section><section className="border border-slate-200 bg-white p-5"><h2 className="font-bold">Lỗi gần đây</h2>{data.errors.slice(0, 6).map((item) => <article key={item.id} className="mt-3 border-l-2 border-slate-200 pl-3"><p lang="ko" className="font-semibold text-slate-800">{item.original_text} → {item.corrected_text}</p><p className="mt-1 text-xs text-slate-500">{item.error_type} · {item.occurrence_count} lần</p></article>)}</section></div></div>;
}
